### ISSUE TITLE
Time series classification with FEDOT?

### ISSUE THREAD

**Issue by j-adamczyk** [aimclub/FEDOT#429]
From the documentation and examples I see that both time series forecasting and tabular classification are possible with FEDOT. But is time series classification also possible? For example, automatic feature extraction to turn time series into tabular format with extracted features and further automatic classification?

**Comment by nicl-nno** [comment]
Hello, Jacub!

The time series classification is not implemented yet, but it can be added to the framework with relatively minor changes.

If you want to make this change by yourself, start from the extending of DataTypesEnum class by 'ts_classification' option and [adding](https://itmo-nss-team.github.io/FEDOT.Docs/contribution/how-to-embed) of automatic feature extraction algorithms (e.g. quantile features, spectral features, etc).

The modification of the pipeline optimizer is not required, since it is model-agnostic by design.

We are ready to help with any questions if necessary.

**Comment by nicl-nno** [comment]
Implemented in https://github.com/aimclub/Fedot.Industrial
